language: python

python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"

env:
 - DJANGO="Django<1.6"
 - DJANGO="Django<1.7"
 - DJANGO="Django<1.8"
 - DJANGO="Django>=1.8"

install:
 - pip install -q $DJANGO
 - pip install -q -e .

cache: pip

script: "python -m extended_choices.tests"

matrix:
  exclude:

    - python: "3.4"
      env: DJANGO="Django<1.6"
    - python: "3.4"
      env: DJANGO="Django<1.7"

    - python: "3.3"
      env: DJANGO="Django<1.6"

    - python: "2.6"
      env: DJANGO="Django<1.8"
    - python: "2.6"
      env: DJANGO="Django>=1.8"
